- name: Homelab
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: server-stats
      servers:
      - type: local
        name: Services
    - size: full
      widgets:

        - type: monitor
          sites:
            

    - size: small
      widgets:
        
